// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using controleDeGastos.Infrastructure.Data;

#nullable disable

namespace controleDeGastos.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260219210840_AddDataDespesa")]
    partial class AddDataDespesa
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("controleDeGastos.Domain.Entities.Ano", b =>
                {
                    b.Property<int>("AnoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AnoId"));

                    b.Property<int>("Numero")
                        .HasColumnType("int");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("AnoId");

                    b.HasIndex("UsuarioId");

                    b.HasIndex("Numero", "UsuarioId")
                        .IsUnique();

                    b.ToTable("Anos");
                });

            modelBuilder.Entity("controleDeGastos.Domain.Entities.CategoriaDespesa", b =>
                {
                    b.Property<int>("CategoriaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoriaId"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("CategoriaId");

                    b.ToTable("CategoriasDespesa");

                    b.HasData(
                        new
                        {
                            CategoriaId = 1,
                            Nome = "Habitação"
                        },
                        new
                        {
                            CategoriaId = 2,
                            Nome = "Transporte"
                        },
                        new
                        {
                            CategoriaId = 3,
                            Nome = "Saúde"
                        },
                        new
                        {
                            CategoriaId = 4,
                            Nome = "Educação"
                        },
                        new
                        {
                            CategoriaId = 5,
                            Nome = "Impostos"
                        },
                        new
                        {
                            CategoriaId = 6,
                            Nome = "Alimentação"
                        },
                        new
                        {
                            CategoriaId = 7,
                            Nome = "Cuidados pessoais"
                        },
                        new
                        {
                            CategoriaId = 8,
                            Nome = "Lazer"
                        },
                        new
                        {
                            CategoriaId = 9,
                            Nome = "Vestuário"
                        },
                        new
                        {
                            CategoriaId = 10,
                            Nome = "Manutenção/prevenção"
                        },
                        new
                        {
                            CategoriaId = 11,
                            Nome = "Outros"
                        });
                });

            modelBuilder.Entity("controleDeGastos.Domain.Entities.Despesa", b =>
                {
                    b.Property<int>("DespesaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DespesaId"));

                    b.Property<DateTime>("DataDespesa")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("DespesaRecorrenteId")
                        .HasColumnType("int");

                    b.Property<int>("MesId")
                        .HasColumnType("int");

                    b.Property<decimal?>("PercentualReceita")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<int>("SubCategoriaId")
                        .HasColumnType("int");

                    b.Property<int>("TipoDespesaId")
                        .HasColumnType("int");

                    b.Property<decimal>("Valor")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("DespesaId");

                    b.HasIndex("DespesaRecorrenteId");

                    b.HasIndex("MesId");

                    b.HasIndex("SubCategoriaId");

                    b.HasIndex("TipoDespesaId");

                    b.ToTable("Despesas");
                });

            modelBuilder.Entity("controleDeGastos.Domain.Entities.DespesaRecorrente", b =>
                {
                    b.Property<int>("DespesaRecorrenteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DespesaRecorrenteId"));

                    b.Property<int>("AnoFim")
                        .HasColumnType("int");

                    b.Property<int>("AnoInicio")
                        .HasColumnType("int");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("MesFim")
                        .HasColumnType("int");

                    b.Property<int>("MesInicio")
                        .HasColumnType("int");

                    b.Property<int>("SubCategoriaId")
                        .HasColumnType("int");

                    b.Property<int>("TipoDespesaId")
                        .HasColumnType("int");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.Property<decimal>("Valor")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("DespesaRecorrenteId");

                    b.HasIndex("SubCategoriaId");

                    b.HasIndex("TipoDespesaId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("DespesasRecorrentes");
                });

            modelBuilder.Entity("controleDeGastos.Domain.Entities.Investimento", b =>
                {
                    b.Property<int>("InvestimentoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("InvestimentoId"));

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("MesId")
                        .HasColumnType("int");

                    b.Property<decimal?>("PercentualReceita")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal>("Valor")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("InvestimentoId");

                    b.HasIndex("MesId");

                    b.ToTable("Investimentos");
                });

            modelBuilder.Entity("controleDeGastos.Domain.Entities.Mes", b =>
                {
                    b.Property<int>("MesId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MesId"));

                    b.Property<int>("AnoId")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("Numero")
                        .HasColumnType("int");

                    b.HasKey("MesId");

                    b.HasIndex("AnoId");

                    b.ToTable("Meses");
                });

            modelBuilder.Entity("controleDeGastos.Domain.Entities.Receita", b =>
                {
                    b.Property<int>("ReceitaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReceitaId"));

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("MesId")
                        .HasColumnType("int");

                    b.Property<decimal>("Valor")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("ReceitaId");

                    b.HasIndex("MesId");

                    b.ToTable("Receitas");
                });

            modelBuilder.Entity("controleDeGastos.Domain.Entities.Saldo", b =>
                {
                    b.Property<int>("SaldoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SaldoId"));

                    b.Property<decimal>("Balanco")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("DespesasAdicionais")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("DespesasExtras")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("DespesasFixas")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("DespesasVariaveis")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Investimentos")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("MesId")
                        .HasColumnType("int");

                    b.Property<string>("Observacao")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<decimal>("Receita")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("SaldoId");

                    b.HasIndex("MesId")
                        .IsUnique();

                    b.ToTable("Saldos");
                });

            modelBuilder.Entity("controleDeGastos.Domain.Entities.SubCategoriaDespesa", b =>
                {
                    b.Property<int>("SubCategoriaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SubCategoriaId"));

                    b.Property<int>("CategoriaId")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("SubCategoriaId");

                    b.HasIndex("CategoriaId");

                    b.ToTable("SubCategoriasDespesa");

                    b.HasData(
                        new
                        {
                            SubCategoriaId = 1,
                            CategoriaId = 1,
                            Nome = "Aluguel"
                        },
                        new
                        {
                            SubCategoriaId = 2,
                            CategoriaId = 1,
                            Nome = "Condomínio"
                        },
                        new
                        {
                            SubCategoriaId = 3,
                            CategoriaId = 1,
                            Nome = "Luz"
                        },
                        new
                        {
                            SubCategoriaId = 4,
                            CategoriaId = 1,
                            Nome = "Água"
                        },
                        new
                        {
                            SubCategoriaId = 5,
                            CategoriaId = 1,
                            Nome = "Spotify"
                        },
                        new
                        {
                            SubCategoriaId = 6,
                            CategoriaId = 1,
                            Nome = "Telefone celular"
                        },
                        new
                        {
                            SubCategoriaId = 7,
                            CategoriaId = 1,
                            Nome = "Gás"
                        },
                        new
                        {
                            SubCategoriaId = 8,
                            CategoriaId = 1,
                            Nome = "Mensalidade TV"
                        },
                        new
                        {
                            SubCategoriaId = 9,
                            CategoriaId = 1,
                            Nome = "Animais"
                        },
                        new
                        {
                            SubCategoriaId = 10,
                            CategoriaId = 1,
                            Nome = "Internet"
                        },
                        new
                        {
                            SubCategoriaId = 11,
                            CategoriaId = 2,
                            Nome = "Prestação da moto"
                        },
                        new
                        {
                            SubCategoriaId = 12,
                            CategoriaId = 2,
                            Nome = "Seguro da moto"
                        },
                        new
                        {
                            SubCategoriaId = 13,
                            CategoriaId = 2,
                            Nome = "Transporte por app"
                        },
                        new
                        {
                            SubCategoriaId = 14,
                            CategoriaId = 2,
                            Nome = "Combustível"
                        },
                        new
                        {
                            SubCategoriaId = 15,
                            CategoriaId = 2,
                            Nome = "Estacionamento"
                        },
                        new
                        {
                            SubCategoriaId = 16,
                            CategoriaId = 6,
                            Nome = "Supermercado"
                        },
                        new
                        {
                            SubCategoriaId = 17,
                            CategoriaId = 6,
                            Nome = "Feira"
                        },
                        new
                        {
                            SubCategoriaId = 18,
                            CategoriaId = 6,
                            Nome = "Hortifruti"
                        },
                        new
                        {
                            SubCategoriaId = 19,
                            CategoriaId = 6,
                            Nome = "Padaria"
                        },
                        new
                        {
                            SubCategoriaId = 20,
                            CategoriaId = 3,
                            Nome = "Plano de saúde"
                        },
                        new
                        {
                            SubCategoriaId = 21,
                            CategoriaId = 3,
                            Nome = "Medicamentos"
                        },
                        new
                        {
                            SubCategoriaId = 22,
                            CategoriaId = 3,
                            Nome = "Consultas"
                        },
                        new
                        {
                            SubCategoriaId = 23,
                            CategoriaId = 4,
                            Nome = "Cursos"
                        },
                        new
                        {
                            SubCategoriaId = 24,
                            CategoriaId = 4,
                            Nome = "Livros"
                        },
                        new
                        {
                            SubCategoriaId = 25,
                            CategoriaId = 8,
                            Nome = "Restaurantes"
                        },
                        new
                        {
                            SubCategoriaId = 26,
                            CategoriaId = 8,
                            Nome = "Cinema"
                        },
                        new
                        {
                            SubCategoriaId = 27,
                            CategoriaId = 8,
                            Nome = "Viagens"
                        },
                        new
                        {
                            SubCategoriaId = 28,
                            CategoriaId = 11,
                            Nome = "Outros"
                        });
                });

            modelBuilder.Entity("controleDeGastos.Domain.Entities.TipoDespesa", b =>
                {
                    b.Property<int>("TipoDespesaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TipoDespesaId"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("TipoDespesaId");

                    b.ToTable("TiposDespesa");

                    b.HasData(
                        new
                        {
                            TipoDespesaId = 1,
                            Nome = "Fixa"
                        },
                        new
                        {
                            TipoDespesaId = 2,
                            Nome = "Variável"
                        },
                        new
                        {
                            TipoDespesaId = 3,
                            Nome = "Extra"
                        },
                        new
                        {
                            TipoDespesaId = 4,
                            Nome = "Adicional"
                        });
                });

            modelBuilder.Entity("controleDeGastos.Domain.Entities.Usuario", b =>
                {
                    b.Property<int>("UsuarioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UsuarioId"));

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("RefreshToken")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("RefreshTokenExpiry")
                        .HasColumnType("datetime2");

                    b.Property<string>("SenhaHash")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("UsuarioId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("controleDeGastos.Domain.Entities.Ano", b =>
                {
                    b.HasOne("controleDeGastos.Domain.Entities.Usuario", "Usuario")
                        .WithMany("Anos")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("controleDeGastos.Domain.Entities.Despesa", b =>
                {
                    b.HasOne("controleDeGastos.Domain.Entities.DespesaRecorrente", "DespesaRecorrente")
                        .WithMany("Despesas")
                        .HasForeignKey("DespesaRecorrenteId");

                    b.HasOne("controleDeGastos.Domain.Entities.Mes", "Mes")
                        .WithMany("Despesas")
                        .HasForeignKey("MesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("controleDeGastos.Domain.Entities.SubCategoriaDespesa", "SubCategoria")
                        .WithMany("Despesas")
                        .HasForeignKey("SubCategoriaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("controleDeGastos.Domain.Entities.TipoDespesa", "TipoDespesa")
                        .WithMany("Despesas")
                        .HasForeignKey("TipoDespesaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DespesaRecorrente");

                    b.Navigation("Mes");

                    b.Navigation("SubCategoria");

                    b.Navigation("TipoDespesa");
                });

            modelBuilder.Entity("controleDeGastos.Domain.Entities.DespesaRecorrente", b =>
                {
                    b.HasOne("controleDeGastos.Domain.Entities.SubCategoriaDespesa", "SubCategoria")
                        .WithMany()
                        .HasForeignKey("SubCategoriaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("controleDeGastos.Domain.Entities.TipoDespesa", "TipoDespesa")
                        .WithMany()
                        .HasForeignKey("TipoDespesaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("controleDeGastos.Domain.Entities.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SubCategoria");

                    b.Navigation("TipoDespesa");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("controleDeGastos.Domain.Entities.Investimento", b =>
                {
                    b.HasOne("controleDeGastos.Domain.Entities.Mes", "Mes")
                        .WithMany("Investimentos")
                        .HasForeignKey("MesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Mes");
                });

            modelBuilder.Entity("controleDeGastos.Domain.Entities.Mes", b =>
                {
                    b.HasOne("controleDeGastos.Domain.Entities.Ano", "Ano")
                        .WithMany("Meses")
                        .HasForeignKey("AnoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ano");
                });

            modelBuilder.Entity("controleDeGastos.Domain.Entities.Receita", b =>
                {
                    b.HasOne("controleDeGastos.Domain.Entities.Mes", "Mes")
                        .WithMany("Receitas")
                        .HasForeignKey("MesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Mes");
                });

            modelBuilder.Entity("controleDeGastos.Domain.Entities.Saldo", b =>
                {
                    b.HasOne("controleDeGastos.Domain.Entities.Mes", "Mes")
                        .WithOne("Saldo")
                        .HasForeignKey("controleDeGastos.Domain.Entities.Saldo", "MesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Mes");
                });

            modelBuilder.Entity("controleDeGastos.Domain.Entities.SubCategoriaDespesa", b =>
                {
                    b.HasOne("controleDeGastos.Domain.Entities.CategoriaDespesa", "Categoria")
                        .WithMany("SubCategorias")
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categoria");
                });

            modelBuilder.Entity("controleDeGastos.Domain.Entities.Ano", b =>
                {
                    b.Navigation("Meses");
                });

            modelBuilder.Entity("controleDeGastos.Domain.Entities.CategoriaDespesa", b =>
                {
                    b.Navigation("SubCategorias");
                });

            modelBuilder.Entity("controleDeGastos.Domain.Entities.DespesaRecorrente", b =>
                {
                    b.Navigation("Despesas");
                });

            modelBuilder.Entity("controleDeGastos.Domain.Entities.Mes", b =>
                {
                    b.Navigation("Despesas");

                    b.Navigation("Investimentos");

                    b.Navigation("Receitas");

                    b.Navigation("Saldo");
                });

            modelBuilder.Entity("controleDeGastos.Domain.Entities.SubCategoriaDespesa", b =>
                {
                    b.Navigation("Despesas");
                });

            modelBuilder.Entity("controleDeGastos.Domain.Entities.TipoDespesa", b =>
                {
                    b.Navigation("Despesas");
                });

            modelBuilder.Entity("controleDeGastos.Domain.Entities.Usuario", b =>
                {
                    b.Navigation("Anos");
                });
#pragma warning restore 612, 618
        }
    }
}
